### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by dee-y** [dsarlo/GeoFood#2]
Hi @dsarlo , glad to find your project again. Would you like a logo for this project? It's free of course as always.

**Comment by dsarlo** [comment]
That would be awesome! By all means, go for it! @dee-y I also have a private repo (currently a school project) and we are looking for a logo for it if you are interested in helping us out? We are looking for a logo that will be in the top left of the windows form as well as on the taskbar. I know you want to show that you are contributing to other git projects, so when we make it public in a few weeks, you could just make a pull request and update the readme with the logo if you want?

**Comment by dee-y** [comment]
Owk that would be fine. Sorry i don't have update on the geofood logo yet, work is really hectic. You will hear from me soon.

**Comment by dsarlo** [comment]
@dee-y Awesome! Take your time! The school application is called word by word. It is essentially a speed reader. Similar to something like this: https://www.spreeder.com/cx/

Thank you.
